export const cc_coins = {
  bitcoin: { name: "Bitcoin", symbol: "BTC", meta: "" },
  ethereum: { name: "Ethereum", symbol: "ETH", meta: "" },
  "binance-coin": { name: "Binance Coin", symbol: "BNB", meta: "" },
  solana: { name: "Solana", symbol: "SOL", meta: "" },
  tether: { name: "Tether", symbol: "USDT", meta: "" },
  cardano: { name: "Cardano", symbol: "ADA", meta: "" },
  xrp: { name: "XRP", symbol: "XRP", meta: "" },
  "polkadot-new": { name: "Polkadot", symbol: "DOT", meta: "" },
  "usd-coin": { name: "USD Coin", symbol: "USDC", meta: "" },
  dogecoin: { name: "Dogecoin", symbol: "DOGE", meta: "" },
  "shiba-inu": { name: "SHIBA INU", symbol: "SHIB", meta: "" },
  "terra-luna": { name: "Terra", symbol: "LUNA", meta: "" },
  avalanche: { name: "Avalanche", symbol: "AVAX", meta: "" },
  litecoin: { name: "Litecoin", symbol: "LTC", meta: "" },
  chainlink: { name: "Chainlink", symbol: "LINK", meta: "" },
  uniswap: { name: "Uniswap", symbol: "UNI", meta: "" },
  "wrapped-bitcoin": { name: "Wrapped Bitcoin", symbol: "WBTC", meta: "" },
  "binance-usd": { name: "Binance USD", symbol: "BUSD", meta: "" },
  "bitcoin-cash": { name: "Bitcoin Cash", symbol: "BCH", meta: "" },
  algorand: { name: "Algorand", symbol: "ALGO", meta: "" },
  polygon: { name: "Polygon", symbol: "MATIC", meta: "" },
  vechain: { name: "VeChain", symbol: "VET", meta: "" },
  stellar: { name: "Stellar", symbol: "XLM", meta: "" },
  "axie-infinity": { name: "Axie Infinity", symbol: "AXS", meta: "" },
  "internet-computer": { name: "Internet Computer", symbol: "ICP", meta: "" },
  tron: { name: "TRON", symbol: "TRX", meta: "" },
  filecoin: { name: "Filecoin", symbol: "FIL", meta: "" },
  cosmos: { name: "Cosmos", symbol: "ATOM", meta: "" },
  "ethereum-classic": { name: "Ethereum Classic", symbol: "ETC", meta: "" },
  theta: { name: "THETA", symbol: "THETA", meta: "" },
  "ftx-token": { name: "FTX Token", symbol: "FTT", meta: "" },
  fantom: { name: "Fantom", symbol: "FTM", meta: "" },
  hedera: { name: "Hedera", symbol: "HBAR", meta: "" },
  "multi-collateral-dai": { name: "Dai", symbol: "DAI", meta: "" },
  "elrond-egld": { name: "Elrond", symbol: "EGLD", meta: "" },
  "near-protocol": { name: "NEAR Protocol", symbol: "NEAR", meta: "" },
  helium: { name: "Helium", symbol: "HNT", meta: "" },
  "the-graph": { name: "The Graph", symbol: "GRT", meta: "" },
  tezos: { name: "Tezos", symbol: "XTZ", meta: "" },
  eos: { name: "EOS", symbol: "EOS", meta: "" },
  monero: { name: "Monero", symbol: "XMR", meta: "" },
  decentraland: { name: "Decentraland", symbol: "MANA", meta: "" },
  loopring: { name: "Loopring", symbol: "LRC", meta: "" },
  pancakeswap: { name: "PancakeSwap", symbol: "CAKE", meta: "" },
  aave: { name: "Aave", symbol: "AAVE", meta: "" },
  flow: { name: "Flow", symbol: "FLOW", meta: "" },
  klaytn: { name: "Klaytn", symbol: "KLAY", meta: "" },
  iota: { name: "IOTA", symbol: "MIOTA", meta: "" },
  kusama: { name: "Kusama", symbol: "KSM", meta: "" },
  ecash: { name: "eCash", symbol: "XEC", meta: "" },
  neo: { name: "Neo", symbol: "NEO", meta: "" },
  thorchain: { name: "THORChain", symbol: "RUNE", meta: "" },
  "bitcoin-sv": { name: "Bitcoin SV", symbol: "BSV", meta: "" },
  quant: { name: "Quant", symbol: "QNT", meta: "" },
  "unus-sed-leo": { name: "UNUS SED LEO", symbol: "LEO", meta: "" },
  harmony: { name: "Harmony", symbol: "ONE", meta: "" },
  maker: { name: "Maker", symbol: "MKR", meta: "" },
  stacks: { name: "Stacks", symbol: "STX", meta: "" },
  zcash: { name: "Zcash", symbol: "ZEC", meta: "" },
  waves: { name: "Waves", symbol: "WAVES", meta: "" },
  bittorrent: { name: "BitTorrent", symbol: "BTT", meta: "" },
  "enjin-coin": { name: "Enjin Coin", symbol: "ENJ", meta: "" },
  amp: { name: "Amp", symbol: "AMP", meta: "" },
  holo: { name: "Holo", symbol: "HOT", meta: "" },
  omg: { name: "OMG Network", symbol: "OMG", meta: "" },
  arweave: { name: "Arweave", symbol: "AR", meta: "" },
  dash: { name: "Dash", symbol: "DASH", meta: "" },
  celo: { name: "Celo", symbol: "CELO", meta: "" },
  "the-sandbox": { name: "The Sandbox", symbol: "SAND", meta: "" },
  compound: { name: "Compound", symbol: "COMP", meta: "" },
  iotex: { name: "IoTeX", symbol: "IOTX", meta: "" },
  nexo: { name: "Nexo", symbol: "NEXO", meta: "" },
  "kucoin-token": { name: "KuCoin Token", symbol: "KCS", meta: "" },
  "theta-fuel": { name: "Theta Fuel", symbol: "TFUEL", meta: "" },
  "curve-dao-token": { name: "Curve DAO Token", symbol: "CRV", meta: "" },
  okb: { name: "OKB", symbol: "OKB", meta: "" },
  nem: { name: "NEM", symbol: "XEM", meta: "" },
  "basic-attention-token": {
    name: "Basic Attention Token",
    symbol: "BAT",
    meta: "",
  },
  qtum: { name: "Qtum", symbol: "QTUM", meta: "" },
  "huobi-token": { name: "Huobi Token", symbol: "HT", meta: "" },
  sushiswap: { name: "SushiSwap", symbol: "SUSHI", meta: "" },
  decred: { name: "Decred", symbol: "DCR", meta: "" },
  icon: { name: "ICON", symbol: "ICX", meta: "" },
  livepeer: { name: "Livepeer", symbol: "LPT", meta: "" },
  revain: { name: "Revain", symbol: "REV", meta: "" },
  ravencoin: { name: "Ravencoin", symbol: "RVN", meta: "" },
  "yearn-finance": { name: "yearn.finance", symbol: "YFI", meta: "" },
  zilliqa: { name: "Zilliqa", symbol: "ZIL", meta: "" },
  secret: { name: "Secret", symbol: "SCRT", meta: "" },
  trueusd: { name: "TrueUSD", symbol: "TUSD", meta: "" },
  "bitcoin-gold": { name: "Bitcoin Gold", symbol: "BTG", meta: "" },
  telcoin: { name: "Telcoin", symbol: "TEL", meta: "" },
  "synthetix-network-token": { name: "Synthetix", symbol: "SNX", meta: "" },
  bancor: { name: "Bancor", symbol: "BNT", meta: "" },
  celsius: { name: "Celsius", symbol: "CEL", meta: "" },
  "0x": { name: "0x", symbol: "ZRX", meta: "" },
  siacoin: { name: "Siacoin", symbol: "SC", meta: "" },
  ankr: { name: "Ankr", symbol: "ANKR", meta: "" },
  uma: { name: "UMA", symbol: "UMA", meta: "" },
  serum: { name: "Serum", symbol: "SRM", meta: "" },
  wax: { name: "WAX", symbol: "WAXP", meta: "" },
  "paxos-standard": { name: "Pax Dollar", symbol: "USDP", meta: "" },
  ontology: { name: "Ontology", symbol: "ONT", meta: "" },
  ren: { name: "Ren", symbol: "REN", meta: "" },
  iostoken: { name: "IOST", symbol: "IOST", meta: "" },
  digibyte: { name: "DigiByte", symbol: "DGB", meta: "" },
  "nervos-network": { name: "Nervos Network", symbol: "CKB", meta: "" },
  xyo: { name: "XYO", symbol: "XYO", meta: "" },
  "1inch": { name: "1inch Network", symbol: "1INCH", meta: "" },
  origintrail: { name: "OriginTrail", symbol: "TRAC", meta: "" },
  nano: { name: "Nano", symbol: "NANO", meta: "" },
  "gnosis-gno": { name: "Gnosis", symbol: "GNO", meta: "" },
  fetch: { name: "Fetch.ai", symbol: "FET", meta: "" },
  dent: { name: "Dent", symbol: "DENT", meta: "" },
  velas: { name: "Velas", symbol: "VLX", meta: "" },
  bakerytoken: { name: "BakeryToken", symbol: "BAKE", meta: "" },
  nucypher: { name: "NuCypher", symbol: "NU", meta: "" },
  "ocean-protocol": { name: "Ocean Protocol", symbol: "OCEAN", meta: "" },
  kava: { name: "Kava", symbol: "KAVA", meta: "" },
  "reserve-rights": { name: "Reserve Rights", symbol: "RSR", meta: "" },
  verge: { name: "Verge", symbol: "XVG", meta: "" },
  "injective-protocol": { name: "Injective Protocol", symbol: "INJ", meta: "" },
  storj: { name: "Storj", symbol: "STORJ", meta: "" },
  "golem-network-tokens": { name: "Golem", symbol: "GLM", meta: "" },
  "alpha-finance-lab": { name: "Alpha Finance Lab", symbol: "ALPHA", meta: "" },
  "polymath-network": { name: "Polymath", symbol: "POLY", meta: "" },
  orchid: { name: "Orchid", symbol: "OXT", meta: "" },
  swipe: { name: "Swipe", symbol: "SXP", meta: "" },
  zel: { name: "Flux", symbol: "FLUX", meta: "" },
  coti: { name: "COTI", symbol: "COTI", meta: "" },
  "vethor-token": { name: "VeThor Token", symbol: "VTHO", meta: "" },
  lisk: { name: "Lisk", symbol: "LSK", meta: "" },
  numeraire: { name: "Numeraire", symbol: "NMR", meta: "" },
  "origin-protocol": { name: "Origin Protocol", symbol: "OGN", meta: "" },
  "fei-usd": { name: "Fei USD", symbol: "FEI", meta: "" },
  "bitcoin-diamond": { name: "Bitcoin Diamond", symbol: "BCD", meta: "" },
  medibloc: { name: "MediBloc", symbol: "MED", meta: "" },
  rlc: { name: "iExec RLC", symbol: "RLC", meta: "" },
  status: { name: "Status", symbol: "SNT", meta: "" },
  "pax-gold": { name: "PAX Gold", symbol: "PAXG", meta: "" },
  "hive-blockchain": { name: "Hive", symbol: "HIVE", meta: "" },
  ardor: { name: "Ardor", symbol: "ARDR", meta: "" },
  ergo: { name: "Ergo", symbol: "ERG", meta: "" },
  "band-protocol": { name: "Band Protocol", symbol: "BAND", meta: "" },
  "oasis-network": { name: "Oasis Network", symbol: "ROSE", meta: "" },
  civic: { name: "Civic", symbol: "CVC", meta: "" },
  prometeus: { name: "Prometeus", symbol: "PROM", meta: "" },
  singularitynet: { name: "SingularityNET", symbol: "AGIX", meta: "" },
  aelf: { name: "aelf", symbol: "ELF", meta: "" },
  casper: { name: "Casper", symbol: "CSPR", meta: "" },
  "energy-web-token": { name: "Energy Web Token", symbol: "EWT", meta: "" },
  stratis: { name: "Stratis", symbol: "STRAX", meta: "" },
  ampleforth: { name: "Ampleforth", symbol: "AMPL", meta: "" },
  orbs: { name: "Orbs", symbol: "ORBS", meta: "" },
  hex: { name: "HEX", symbol: "HEX", meta: "" },
  "the-transfer-token": { name: "The Transfer Token", symbol: "TTT", meta: "" },
  defichain: { name: "DeFiChain", symbol: "DFI", meta: "" },
  frax: { name: "Frax", symbol: "FRAX", meta: "" },
  whitecoin: { name: "WhiteCoin", symbol: "XWC", meta: "" },
  "keep-network": { name: "Keep Network", symbol: "KEEP", meta: "" },
  "frax-share": { name: "Frax Share", symbol: "FXS", meta: "" },
  electroneum: { name: "Electroneum", symbol: "ETN", meta: "" },
  "pirate-chain": { name: "Pirate Chain", symbol: "ARRR", meta: "" },
  "akash-network": { name: "Akash Network", symbol: "AKT", meta: "" },
  centrality: { name: "Centrality", symbol: "CENNZ", meta: "" },
  hedgetrade: { name: "HedgeTrade", symbol: "HEDG", meta: "" },
  augur: { name: "Augur", symbol: "REP", meta: "" },
  husd: { name: "HUSD", symbol: "HUSD", meta: "" },
  proton: { name: "Proton", symbol: "XPR", meta: "" },
  "mirror-protocol": { name: "Mirror Protocol", symbol: "MIR", meta: "" },
  ark: { name: "Ark", symbol: "ARK", meta: "" },
  syscoin: { name: "Syscoin", symbol: "SYS", meta: "" },
  phantasma: { name: "Phantasma", symbol: "SOUL", meta: "" },
  enzyme: { name: "Enzyme", symbol: "MLN", meta: "" },
  steem: { name: "Steem", symbol: "STEEM", meta: "" },
  maidsafecoin: { name: "MaidSafeCoin", symbol: "MAID", meta: "" },
  "crypto-com": { name: "MCO", symbol: "MCO", meta: "" },
  "rsk-infrastructure-framework": {
    name: "RSK Infrastructure Framework",
    symbol: "RIF",
    meta: "",
  },
  request: { name: "Request", symbol: "REQ", meta: "" },
  "arpa-chain": { name: "ARPA Chain", symbol: "ARPA", meta: "" },
  tomochain: { name: "TomoChain", symbol: "TOMO", meta: "" },
  metal: { name: "Metal", symbol: "MTL", meta: "" },
  kin: { name: "Kin", symbol: "KIN", meta: "" },
  propy: { name: "Propy", symbol: "PRO", meta: "" },
  syntropy: { name: "Syntropy", symbol: "NOIA", meta: "" },
  "uquid-coin": { name: "Uquid Coin", symbol: "UQC", meta: "" },
  aragon: { name: "Aragon", symbol: "ANT", meta: "" },
  utrust: { name: "Utrust", symbol: "UTK", meta: "" },
  "haven-protocol": { name: "Haven Protocol", symbol: "XHV", meta: "" },
  just: { name: "JUST", symbol: "JST", meta: "" },
  wanchain: { name: "Wanchain", symbol: "WAN", meta: "" },
  "smooth-love-potion": { name: "Smooth Love Potion", symbol: "SLP", meta: "" },
  quarkchain: { name: "QuarkChain", symbol: "QKC", meta: "" },
  barnbridge: { name: "BarnBridge", symbol: "BOND", meta: "" },
  "abbc-coin": { name: "ABBC Coin", symbol: "ABBC", meta: "" },
  everipedia: { name: "Everipedia", symbol: "IQ", meta: "" },
  "power-ledger": { name: "Powerledger", symbol: "POWR", meta: "" },
  "molecular-future": { name: "Molecular Future", symbol: "MOF", meta: "" },
  balancer: { name: "Balancer", symbol: "BAL", meta: "" },
  "zb-token": { name: "ZB Token", symbol: "ZB", meta: "" },
  handshake: { name: "Handshake", symbol: "HNS", meta: "" },
  safepal: { name: "SafePal", symbol: "SFP", meta: "" },
  "gemini-dollar": { name: "Gemini Dollar", symbol: "GUSD", meta: "" },
  derivadao: { name: "DerivaDAO", symbol: "DDX", meta: "" },
  bitshares: { name: "BitShares", symbol: "BTS", meta: "" },
  idex: { name: "IDEX", symbol: "IDEX", meta: "" },
  divi: { name: "Divi", symbol: "DIVI", meta: "" },
  metadium: { name: "Metadium", symbol: "META", meta: "" },
  irisnet: { name: "IRISnet", symbol: "IRIS", meta: "" },
  tellor: { name: "Tellor", symbol: "TRB", meta: "" },
  komodo: { name: "Komodo", symbol: "KMD", meta: "" },
  mxc: { name: "MXC", symbol: "MXC", meta: "" },
  chimpion: { name: "Chimpion", symbol: "BNANA", meta: "" },
  akropolis: { name: "Akropolis", symbol: "AKRO", meta: "" },
  "bzx-protocol": { name: "bZx Protocol", symbol: "BZRX", meta: "" },
  hackenai: { name: "Hacken Token", symbol: "HAI", meta: "" },
  monacoin: { name: "MonaCoin", symbol: "MONA", meta: "" },
  district0x: { name: "district0x", symbol: "DNT", meta: "" },
  strong: { name: "Strong", symbol: "STRONG", meta: "" },
  streamr: { name: "Streamr", symbol: "DATA", meta: "" },
  elastos: { name: "Elastos", symbol: "ELA", meta: "" },
  "loom-network": { name: "Loom Network", symbol: "LOOM", meta: "" },
  ramp: { name: "RAMP", symbol: "RAMP", meta: "" },
  "lto-network": { name: "LTO Network", symbol: "LTO", meta: "" },
  "thunder-token": { name: "Thunder Token", symbol: "TT", meta: "" },
  "beefy-finance": { name: "Beefy Finance", symbol: "BIFI", meta: "" },
  "adx-net": { name: "Ambire AdEx", symbol: "ADX", meta: "" },
  presearch: { name: "Presearch", symbol: "PRE", meta: "" },
  xdai: { name: "xDai", symbol: "STAKE", meta: "" },
  parsiq: { name: "PARSIQ", symbol: "PRQ", meta: "" },
  sora: { name: "Sora", symbol: "XOR", meta: "" },
  gas: { name: "Gas", symbol: "GAS", meta: "" },
  bytom: { name: "Bytom", symbol: "BTM", meta: "" },
  aion: { name: "Aion", symbol: "AION", meta: "" },
  bluzelle: { name: "Bluzelle", symbol: "BLZ", meta: "" },
  "mantra-dao": { name: "MANTRA DAO", symbol: "OM", meta: "" },
  waltonchain: { name: "Waltonchain", symbol: "WTC", meta: "" },
  redd: { name: "ReddCoin", symbol: "RDD", meta: "" },
  groestlcoin: { name: "Groestlcoin", symbol: "GRS", meta: "" },
  kleros: { name: "Kleros", symbol: "PNK", meta: "" },
  "bytecoin-bcn": { name: "Bytecoin", symbol: "BCN", meta: "" },
  nimiq: { name: "Nimiq", symbol: "NIM", meta: "" },
  digixdao: { name: "DigixDAO", symbol: "DGD", meta: "" },
  dragonchain: { name: "Dragonchain", symbol: "DRGN", meta: "" },
  beam: { name: "Beam", symbol: "BEAM", meta: "" },
  "steem-dollars": { name: "Steem Dollars", symbol: "SBD", meta: "" },
  "apollo-currency": { name: "Apollo Currency", symbol: "APL", meta: "" },
  rchain: { name: "RChain", symbol: "REV", meta: "" },
  dock: { name: "Dock", symbol: "DOCK", meta: "" },
  vite: { name: "VITE", symbol: "VITE", meta: "" },
  latoken: { name: "LATOKEN", symbol: "LA", meta: "" },
  airswap: { name: "AirSwap", symbol: "AST", meta: "" },
  veritaseum: { name: "Veritaseum", symbol: "VERI", meta: "" },
  torn: { name: "Tornado Cash", symbol: "TORN", meta: "" },
  nuls: { name: "NULS", symbol: "NULS", meta: "" },
  aeternity: { name: "Aeternity", symbol: "AE", meta: "" },
  "cream-finance": { name: "Cream Finance", symbol: "CREAM", meta: "" },
  "saffron-finance": { name: "saffron.finance", symbol: "SFI", meta: "" },
  "v-systems": { name: "v.systems", symbol: "VSYS", meta: "" },
  pivx: { name: "PIVX", symbol: "PIVX", meta: "" },
  gxchain: { name: "GXChain", symbol: "GXC", meta: "" },
  mithril: { name: "Mithril", symbol: "MITH", meta: "" },
  counterparty: { name: "Counterparty", symbol: "XCP", meta: "" },
  peercoin: { name: "Peercoin", symbol: "PPC", meta: "" },
  likecoin: { name: "LikeCoin", symbol: "LIKE", meta: "" },
  lamden: { name: "Lamden", symbol: "TAU", meta: "" },
  "raiden-network-token": {
    name: "Raiden Network Token",
    symbol: "RDN",
    meta: "",
  },
  chainx: { name: "ChainX", symbol: "PCX", meta: "" },
  mimblewimblecoin: { name: "MimbleWimbleCoin", symbol: "MWC", meta: "" },
  perlin: { name: "PERL.eco", symbol: "PERL", meta: "" },
  populous: { name: "Populous", symbol: "PPT", meta: "" },
  wing: { name: "Wing Finance", symbol: "WING", meta: "" },
  switcheo: { name: "Switcheo", symbol: "SWTH", meta: "" },
  quantstamp: { name: "Quantstamp", symbol: "QSP", meta: "" },
  pnetwork: { name: "pNetwork", symbol: "PNT", meta: "" },
  nexus: { name: "Nexus", symbol: "NXS", meta: "" },
  "karma-eos": { name: "KARMA", symbol: "KARMA", meta: "" },
  vertcoin: { name: "Vertcoin", symbol: "VTC", meta: "" },
  cortex: { name: "Cortex", symbol: "CTXC", meta: "" },
  gamecredits: { name: "GameCredits", symbol: "GAME", meta: "" },
  grin: { name: "Grin", symbol: "GRIN", meta: "" },
  gifto: { name: "Gifto", symbol: "GTO", meta: "" },
  fusion: { name: "Fusion", symbol: "FSN", meta: "" },
  vesper: { name: "Vesper", symbol: "VSP", meta: "" },
  cindicator: { name: "Cindicator", symbol: "CND", meta: "" },
  banano: { name: "Banano", symbol: "BAN", meta: "" },
  santiment: { name: "Santiment Network Token", symbol: "SAN", meta: "" },
  waykichain: { name: "WaykiChain", symbol: "WICC", meta: "" },
  obyte: { name: "Obyte", symbol: "GBYTE", meta: "" },
  "sonm-bep20": { name: "SONM (BEP-20)", symbol: "SNM", meta: "" },
  aurora: { name: "Aurora", symbol: "AOA", meta: "" },
  bankera: { name: "Bankera", symbol: "BNK", meta: "" },
  "measurable-data-token": {
    name: "Measurable Data Token",
    symbol: "MDT",
    meta: "",
  },
  "nav-coin": { name: "Navcoin", symbol: "NAV", meta: "" },
  namecoin: { name: "Namecoin", symbol: "NMC", meta: "" },
  "nebulas-token": { name: "Nebulas", symbol: "NAS", meta: "" },
  hypercash: { name: "HyperCash", symbol: "HC", meta: "" },
  qash: { name: "QASH", symbol: "QASH", meta: "" },
  "nest-protocol": { name: "NEST Protocol", symbol: "NEST", meta: "" },
  crpt: { name: "Crypterium", symbol: "CRPT", meta: "" },
  suterusu: { name: "suterusu", symbol: "SUTER", meta: "" },
  metaverse: { name: "Metaverse ETP", symbol: "ETP", meta: "" },
  "deepbrain-chain": { name: "DeepBrain Chain", symbol: "DBC", meta: "" },
  neblio: { name: "Neblio", symbol: "NEBL", meta: "" },
  foam: { name: "FOAM", symbol: "FOAM", meta: "" },
  amber: { name: "Ambrosus", symbol: "AMB", meta: "" },
  "88mph": { name: "88mph", symbol: "MPH", meta: "" },
  "nucleus-vision": { name: "Nucleus Vision", symbol: "NCASH", meta: "" },
  "library-credits": { name: "LBRY Credits", symbol: "LBC", meta: "" },
  oax: { name: "OAX", symbol: "OAX", meta: "" },
  appcoins: { name: "AppCoins", symbol: "APPC", meta: "" },
  "quantum-resistant-ledger": {
    name: "Quantum Resistant Ledger",
    symbol: "QRL",
    meta: "",
  },
  polyswarm: { name: "PolySwarm", symbol: "NCT", meta: "" },
  arcblock: { name: "Arcblock", symbol: "ABT", meta: "" },
  particl: { name: "Particl", symbol: "PART", meta: "" },
  nxt: { name: "Nxt", symbol: "NXT", meta: "" },
  ignis: { name: "Ignis", symbol: "IGNIS", meta: "" },
  mysterium: { name: "Mysterium", symbol: "MYST", meta: "" },
  "aidos-kuneen": { name: "Aidos Kuneen", symbol: "ADK", meta: "" },
  "bitforex-token": { name: "BitForex Token", symbol: "BF", meta: "" },
  tenx: { name: "TenX", symbol: "PAY", meta: "" },
  iqeon: { name: "IQeon", symbol: "IQN", meta: "" },
  bread: { name: "Bread", symbol: "BRD", meta: "" },
  monetha: { name: "Monetha", symbol: "MTH", meta: "" },
  factom: { name: "Factom", symbol: "FCT", meta: "" },
  "bitcoin-private": { name: "Bitcoin Private", symbol: "BTCP", meta: "" },
  dentacoin: { name: "Dentacoin", symbol: "DCN", meta: "" },
  salt: { name: "SALT", symbol: "SALT", meta: "" },
  everex: { name: "Everex", symbol: "EVX", meta: "" },
  tokenomy: { name: "Tokenomy", symbol: "TEN", meta: "" },
  "litecoin-cash": { name: "Litecoin Cash", symbol: "LCC", meta: "" },
  meetone: { name: "MEET.ONE", symbol: "MEETONE", meta: "" },
  "moeda-loyalty-points": {
    name: "Moeda Loyalty Points",
    symbol: "MDA",
    meta: "",
  },
  diamond: { name: "Diamond", symbol: "DMD", meta: "" },
  kambria: { name: "Kambria", symbol: "KAT", meta: "" },
  lympo: { name: "Lympo", symbol: "LYM", meta: "" },
  primecoin: { name: "Primecoin", symbol: "XPM", meta: "" },
  "agoras-tokens": { name: "Agoras", symbol: "AGRS", meta: "" },
  hord: { name: "Hord", symbol: "HORD", meta: "" },
  "all-sports": { name: "All Sports", symbol: "SOC", meta: "" },
  cybervein: { name: "CyberVein", symbol: "CVT", meta: "" },
  "ripio-credit-network": {
    name: "Ripio Credit Network",
    symbol: "RCN",
    meta: "",
  },
  einsteinium: { name: "Einsteinium", symbol: "EMC2", meta: "" },
  yoyow: { name: "YOYOW", symbol: "YOYOW", meta: "" },
  autonio: { name: "Autonio", symbol: "NIOX", meta: "" },
  "high-performance-blockchain": {
    name: "High Performance Blockchain",
    symbol: "HPB",
    meta: "",
  },
  achain: { name: "Achain", symbol: "ACT", meta: "" },
  turtlecoin: { name: "TurtleCoin", symbol: "TRTL", meta: "" },
  ubiq: { name: "Ubiq", symbol: "UBQ", meta: "" },
  monolith: { name: "Monolith", symbol: "TKN", meta: "" },
  "time-new-bank": { name: "Time New Bank", symbol: "TNB", meta: "" },
  blocknet: { name: "Blocknet", symbol: "BLOCK", meta: "" },
  "html-coin": { name: "HTMLCOIN", symbol: "HTML", meta: "" },
  pillar: { name: "Pillar", symbol: "PLR", meta: "" },
  digitalnote: { name: "DigitalNote", symbol: "XDN", meta: "" },
  newton: { name: "Newton", symbol: "NEW", meta: "" },
  "hakka-finance": { name: "Hakka.Finance", symbol: "HAKKA", meta: "" },
  "iot-chain": { name: "IoT Chain", symbol: "ITC", meta: "" },
  egretia: { name: "Egretia", symbol: "EGT", meta: "" },
  credits: { name: "Credits", symbol: "CS", meta: "" },
  qlink: { name: "QLC Chain", symbol: "QLC", meta: "" },
  gulden: { name: "Gulden", symbol: "NLG", meta: "" },
  aeon: { name: "Aeon", symbol: "AEON", meta: "" },
  cybermiles: { name: "CyberMiles", symbol: "CMT", meta: "" },
  skycoin: { name: "Skycoin", symbol: "SKY", meta: "" },
  viacoin: { name: "Viacoin", symbol: "VIA", meta: "" },
  vibe: { name: "VIBE", symbol: "VIBE", meta: "" },
  smartcash: { name: "SmartCash", symbol: "SMART", meta: "" },
  medishares: { name: "MediShares", symbol: "MDS", meta: "" },
  edgeless: { name: "Edgeless", symbol: "EDG", meta: "" },
  "sirin-labs-token": { name: "SIRIN LABS Token", symbol: "SRN", meta: "" },
  myriad: { name: "Myriad", symbol: "XMY", meta: "" },
  pumapay: { name: "PumaPay", symbol: "PMA", meta: "" },
  wagerr: { name: "Wagerr", symbol: "WGR", meta: "" },
  "bibox-token": { name: "Bibox Token", symbol: "BIX", meta: "" },
  ruff: { name: "Ruff", symbol: "RUFF", meta: "" },
  feathercoin: { name: "Feathercoin", symbol: "FTC", meta: "" },
  pluton: { name: "Pluton", symbol: "PLU", meta: "" },
  bitcoinz: { name: "BitcoinZ", symbol: "BTCZ", meta: "" },
  bitcore: { name: "BitCore", symbol: "BTX", meta: "" },
  data: { name: "DATA", symbol: "DTA", meta: "" },
  potcoin: { name: "PotCoin", symbol: "POT", meta: "" },
  xmax: { name: "XMax", symbol: "XMX", meta: "" },
  ost: { name: "OST", symbol: "OST", meta: "" },
  eboostcoin: { name: "eBoost", symbol: "EBST", meta: "" },
  blackcoin: { name: "BlackCoin", symbol: "BLK", meta: "" },
  "add-xyz": { name: "Add.xyz", symbol: "ADD", meta: "" },
  tokes: { name: "Tokes", symbol: "TKS", meta: "" },
  sumokoin: { name: "Sumokoin", symbol: "SUMO", meta: "" },
  "global-social-chain": {
    name: "Global Social Chain",
    symbol: "GSC",
    meta: "",
  },
  wings: { name: "Wings", symbol: "WINGS", meta: "" },
  wepower: { name: "WePower", symbol: "WPR", meta: "" },
  pinkcoin: { name: "Pinkcoin", symbol: "PINK", meta: "" },
  gridcoin: { name: "Gridcoin", symbol: "GRC", meta: "" },
  snowswap: { name: "SnowSwap", symbol: "SNOW", meta: "" },
  educare: { name: "EDUCare", symbol: "EKT", meta: "" },
  tera: { name: "TERA", symbol: "TERA", meta: "" },
  emercoin: { name: "Emercoin", symbol: "EMC", meta: "" },
  xensor: { name: "Xensor", symbol: "XSR", meta: "" },
  cloakcoin: { name: "CloakCoin", symbol: "CLOAK", meta: "" },
  seele: { name: "Seele-N", symbol: "SEELE", meta: "" },
  "bean-cash": { name: "Bean Cash", symbol: "BITB", meta: "" },
  ongsocial: { name: "SoMee.Social [OLD]", symbol: "ONG", meta: "" },
  polis: { name: "Polis", symbol: "POLIS", meta: "" },
  fujicoin: { name: "FujiCoin", symbol: "FJC", meta: "" },
  "bitcoin-plus": { name: "Bitcoin Plus", symbol: "XBC", meta: "" },
  "agrello-delta": { name: "Agrello", symbol: "DLT", meta: "" },
  paypie: { name: "PayPie", symbol: "PPP", meta: "" },
  okcash: { name: "OKCash", symbol: "OK", meta: "" },
  ion: { name: "ION", symbol: "ION", meta: "" },
  "ryo-currency": { name: "Ryo Currency", symbol: "RYO", meta: "" },
  "digital-reserve-currency": {
    name: "Digital Reserve Currency",
    symbol: "DRC",
    meta: "",
  },
  omni: { name: "Omni", symbol: "OMNI", meta: "" },
  "genesis-vision": { name: "Genesis Vision", symbol: "GVT", meta: "" },
  kanadecoin: { name: "KanadeCoin", symbol: "KNDC", meta: "" },
  chatcoin: { name: "ChatCoin", symbol: "CHAT", meta: "" },
  crown: { name: "Crown", symbol: "CRW", meta: "" },
  vericoin: { name: "VeriCoin", symbol: "VRC", meta: "" },
  tokenpay: { name: "TokenPay", symbol: "TPAY", meta: "" },
  karbo: { name: "Karbo", symbol: "KRB", meta: "" },
  veil: { name: "Veil", symbol: "VEIL", meta: "" },
  faceter: { name: "Faceter", symbol: "FACE", meta: "" },
  patientory: { name: "Patientory", symbol: "PTOY", meta: "" },
  substratum: { name: "Substratum", symbol: "SUB", meta: "" },
  hydro: { name: "Hydro", symbol: "HYDRO", meta: "" },
  zclassic: { name: "ZClassic", symbol: "ZCL", meta: "" },
  colossusxt: { name: "ColossusXT", symbol: "COLX", meta: "" },
  "2key-network": { name: "2key.network", symbol: "2KEY", meta: "" },
  esbc: { name: "ESBC", symbol: "ESBC", meta: "" },
  enigma: { name: "Enigma", symbol: "ENG", meta: "" },
  rise: { name: "Rise", symbol: "RISE", meta: "" },
  dmarket: { name: "DMarket", symbol: "DMT", meta: "" },
  sophiatx: { name: "SophiaTX", symbol: "SPHTX", meta: "" },
  hush: { name: "Hush", symbol: "HUSH", meta: "" },
  expanse: { name: "Expanse", symbol: "EXP", meta: "" },
  tigercash: { name: "TigerCash", symbol: "TCH", meta: "" },
  bottos: { name: "Bottos", symbol: "BTO", meta: "" },
  xtrabytes: { name: "XTRABYTES", symbol: "XBY", meta: "" },
  datum: { name: "Datum", symbol: "DAT", meta: "" },
  dether: { name: "Dether", symbol: "DTH", meta: "" },
  etherparty: { name: "Etherparty", symbol: "FUEL", meta: "" },
  pascal: { name: "Pascal", symbol: "PASC", meta: "" },
  masari: { name: "Masari", symbol: "MSR", meta: "" },
  "golos-blockchain": { name: "Golos Blockchain", symbol: "GLS", meta: "" },
  sibcoin: { name: "SIBCoin", symbol: "SIB", meta: "" },
  ink: { name: "Ink", symbol: "INK", meta: "" },
  shipchain: { name: "ShipChain", symbol: "SHIP", meta: "" },
  "trinity-network-credit": {
    name: "Trinity Network Credit",
    symbol: "TNC",
    meta: "",
  },
  poet: { name: "Po.et", symbol: "POE", meta: "" },
  domraider: { name: "DomRaider", symbol: "DRT", meta: "" },
  gobyte: { name: "GoByte", symbol: "GBX", meta: "" },
  asch: { name: "Asch", symbol: "XAS", meta: "" },
  blockmason: { name: "Blockmason Credit Protocol", symbol: "BCPT", meta: "" },
  bounty0x: { name: "Bounty0x", symbol: "BNTY", meta: "" },
  startcoin: { name: "Startcoin", symbol: "START", meta: "" },
  lunyr: { name: "Lunyr", symbol: "LUN", meta: "" },
  belacoin: { name: "Bela", symbol: "BELA", meta: "" },
  tokenbox: { name: "Tokenbox", symbol: "TBX", meta: "" },
  trezarcoin: { name: "TrezarCoin", symbol: "TZC", meta: "" },
  cobinhood: { name: "Cobinhood", symbol: "COB", meta: "" },
  "ether-zero": { name: "Ether Zero", symbol: "ETZ", meta: "" },
  allsafe: { name: "AllSafe", symbol: "ASAFE", meta: "" },
  "internet-of-people": { name: "Internet of People", symbol: "IOP", meta: "" },
  bitsend: { name: "BitSend", symbol: "BSD", meta: "" },
  blocktix: { name: "Blocktix", symbol: "TIX", meta: "" },
  commercium: { name: "Commercium", symbol: "CMM", meta: "" },
  pirl: { name: "Pirl", symbol: "PIRL", meta: "" },
  bitcloud: { name: "Bitcloud", symbol: "BTDX", meta: "" },
  ellaism: { name: "Ellaism", symbol: "ELLA", meta: "" },
  "swarm-city": { name: "Swarm City", symbol: "SWT", meta: "" },
  paypex: { name: "Paypex", symbol: "PAYX", meta: "" },
  xpa: { name: "XPA", symbol: "XPA", meta: "" },
  straks: { name: "STRAKS", symbol: "STAK", meta: "" },
  aeron: { name: "Aeron", symbol: "ARNX", meta: "" },
  "compound-dai": { name: "Compound Dai", symbol: "CDAI", meta: "" },
  "compound-usd-coin": { name: "Compound USD Coin", symbol: "CUSDC", meta: "" },
  "compound-usdt": { name: "Compound USDT", symbol: "CUSDT", meta: "" },
  pearl: { name: "Pearl", symbol: "PEARL", meta: "" },
  elongate: { name: "ELONGATE", symbol: "ELONGATE", meta: "" },
  "tether-gold": { name: "Tether Gold", symbol: "XAUT", meta: "" },
  "coinmetro-token": { name: "CoinMetro Token", symbol: "XCM", meta: "" },
  "gincoin-global-interest-rate": {
    name: "GINCOIN (Global  Interest  Rate)",
    symbol: "GIN",
    meta: "",
  },
  zelwin: { name: "Zelwin", symbol: "ZLW", meta: "" },
  poocoin: { name: "PooCoin", symbol: "POOCOIN", meta: "" },
  "exchange-union": { name: "Exchange Union", symbol: "XUC", meta: "" },
  naga: { name: "NAGA", symbol: "NGC", meta: "" },
  reserve: { name: "Reserve", symbol: "RSV", meta: "" },
  mixin: { name: "Mixin", symbol: "XIN", meta: "" },
  neumark: { name: "Neumark", symbol: "NEU", meta: "" },
  monnos: { name: "MONNOS", symbol: "MNS", meta: "" },
  kingmoney: { name: "KingMoney", symbol: "KIM", meta: "" },
  "ptokens-btc": { name: "pTokens BTC", symbol: "PBTC", meta: "" },
  "pundi-x": { name: "Pundi X[old]", symbol: "NPXS", meta: "" },
  ternio: { name: "Ternio", symbol: "TERN", meta: "" },
  odem: { name: "ODEM", symbol: "ODE", meta: "" },
  salus: { name: "SaluS", symbol: "SLS", meta: "" },
  cloudcoin: { name: "CloudCoin", symbol: "CCE", meta: "" },
  "largo-coin": { name: "Largo Coin", symbol: "LRG", meta: "" },
  lykke: { name: "Lykke", symbol: "LKK", meta: "" },
  nolimitcoin: { name: "NoLimitCoin", symbol: "NLC2", meta: "" },
  torex: { name: "Torex", symbol: "TOR", meta: "" },
  polybius: { name: "Polybius", symbol: "PLBT", meta: "" },
  electra: { name: "Electra", symbol: "ECA", meta: "" },
  clams: { name: "Clams", symbol: "CLAM", meta: "" },
  spankchain: { name: "SpankChain", symbol: "SPANK", meta: "" },
  moac: { name: "MOAC", symbol: "MOAC", meta: "" },
  "karatgold-coin": { name: "Karatgold Coin", symbol: "KBC", meta: "" },
  "insight-chain": { name: "Insight Chain", symbol: "INB", meta: "" },
  thorecoin: { name: "ThoreCoin", symbol: "THR", meta: "" },
  blockstamp: { name: "BlockStamp", symbol: "BST", meta: "" },
};
